### ISSUE TITLE
Demensions not loading

### ISSUE THREAD

**Issue by Toekneeeeeeeeee** [MarkusBordihn/BOs-Lobby#12]
**Describe the bug**

**To Reproduce**
/lobby in minecraft comes up with the text "Unable to teleport to Lobby, because lobby:lobby_dimension  dimension is not loaded!

**Expected behavior**
teleport us to lobby

**Screenshots**
![image](https://user-images.githubusercontent.com/52366498/187050496-c22b97e4-ca09-45ac-9008-6395c1dd7ab1.png)

**Debugging**
game does not crash

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
i dont believe so

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the report, please check the FAQ which describe this issue like:

**I installed the mod, but it is not working?**
There are some mods which blocking the custom dimension creation until they have created their custom dimensions.
If this happens other mods are not able to create their customer dimension on the first start.
Normally the issue is fixed by just restarting the server, you will additionally see a message in the log if this is needed.

If you still run into issues, please add your log file to this report and I will take a closer look.

**Comment by Toekneeeeeeeeee** [comment]
We tried restarting the server and there was still no change.  I have
attached the recent log file for our server.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback, unfortunately I can't find any attached log. 
Please use a secret gist like https://gist.github.com/ or something similar to share the file with this report.

Alternative, you could perform the following steps in the mean time:

**Client Steps**
- Install the mod on the client
- Start a new world and visit each lobby dimension once
- Stop the client

**Server Steps**
- Create a backup of your server
- Stop the server
- Empty the /dimensions/lobby directory, if needed
- Copy the corresponding /dimensions/lobby files from the client to the server directory
- Start the server

Because the dimension creation is a standard feature in most of the case a modified client /server or an mod is the issue.
But once the files are on the server it should work without any issue, regardless of the underlying issue.

**Comment by Toekneeeeeeeeee** [comment]
I pasted the log in the secret gist.

https://gist.github.com/Toekneeeeeeeeee/c0bebc8baee421ba863e8874318c397b

Let me know if you need any other info.

**Comment by MarkusBordihn** [comment]
Thanks for the log, I can see that you are using a deprecated version 1.18.1.

I recommend switching to 1.18.2 as soon as possible, because 1.18.1 is known to have problems with dimensions, mods and datapacks. Furthermore most of the mods are no longer updated for 1.18.1. 

Anyways I updated the 1.18.1 version with the latest update from 1.18.2, which maybe fix your issue.

Please try the following steps

- Stop the server.
- Delete your `/dimensions/lobby` from your world directory.
- Update the mod with [`lobby_1.18.1-3.1.0.jar`](https://www.curseforge.com/minecraft/mc-mods/lobby/files/3960937)
- Start the server
- Check if you could use the command, if not restart the server once or two times

If the dimensions are still not created you could only upgrade to 1.18.2 or you can follow the steps from https://github.com/MarkusBordihn/BOs-Lobby/issues/12#issuecomment-1230555085 to manually copy a pre-generated dimension to your server.
